use_sim_time: False
start_time_sec: 1693460256
start_time_nsec: 415760183
ignore_polarity: True
time_surface_mode: 0 # 0: Backward; 1: Forward
decay_ms: 25
median_blur_kernel_size: 1
max_event_queue_len: 1
event_accumulate_number: 8000